name: hassfest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Home Assistant
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
      - name: Validate
        run: |
          hassfest validate
          hassfest translation
      - name: Check manifest
        run: |
          python -c "
          import json
          with open('custom_components/lambda_heat_pumps/manifest.json') as f:
              manifest = json.load(f)
          required_fields = ['domain', 'name', 'version', 'config_flow', 'documentation', 'issue_tracker', 'requirements', 'codeowners', 'iot_class']
          missing = [field for field in required_fields if field not in manifest]
          if missing:
              print(f'Missing required fields in manifest.json: {missing}')
              exit(1)
          print('Manifest validation passed')
          " 
